### ISSUE TITLE
Subs in vline mode

### ISSUE THREAD

**Issue by cenk1cenk2** [johmsalas/text-case.nvim#24]
Hello @johmsalas,

Thanks for creating this beautiful plugin, subs mode is the most useful plugin I have ever encountered in any plugin. But I do recently have a problem with it when I go into the v-line mode it fails to scope for me. You can find the details in the clip below.

[recording_20220901-221900.webm](https://user-images.githubusercontent.com/26881592/188004853-ac73741f-bf9a-40b9-aa7c-bc50645ab5b4.webm)

**Comment by cenk1cenk2** [comment]
Hello @johmsalas ,

Thanks for your response and I sincerely want to thank you for maintaining the plugin, since it has been something that I was yearning for quite some time.

The first error from the nvim-surround was a fluke, but as mentioned the second one is in V-Line mode trying to do the swap and the third one just works without any scoping.

A code sample like below is the one in the video.
```yml
.dotnet-project-business-api-mobile-aggregator: &dotnet-project-business-api-mobile-aggregator
  PROJECT_CWD: ./src/gateways/mobile-api/Sorwe.Business.MobileApi.HttpAggregator/
  PROJECT_FILE: Sorwe.Business.MobileApi.HttpAggregator.csproj
  NUGET_FILE: ./nuget.config
```
